@startuml 用户流程
skinparam actorStyle awesome
actor 用户
autonumber "<b>."
用户->Github:Push
Github->后端服务:GithubAction\n携带整体Json文件
后端服务->翻译API:自脚本执行，携带值
后端服务<-翻译API:翻译携带值
后端服务->后端服务:处理翻译结果，生成Json文件
后端服务->Github:提交Json文件
Github->用户:发送消息“自动化流程完成”
@enduml