name: Test

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        run: |
          echo "ls -la"
          ls -la
          echo "pwd"
          pwd
          echo "whoami"
          whoami
          echo "hostname"
          hostname
          echo "date"
          date
          echo "env"
          env
