name: APITest and push

on:
  push:
    branches:
      - main
    paths:
      - "Docs/**/*.md"
      - "language/**/*.json"
      - "*.md"

permissions:
  contents: write

jobs:
  APITest_and_push:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
    steps:
      - name: 安装node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 输出node版本
        run: |
          node -v
          npm -v

      - name: Checkout
        uses: actions/checkout@v4

      - name: 输出目录
        run: |
          pwd

      - name: 安装依赖
        run: |
          npm install

      - name: 测试通过Secrets输出的GEMINI_API_KEY的长度
        run: |
          if [ -z "$GEMINI_API_KEY"];then
              echo "$GEMINI_API_KEY的长度为0"
          else
              echo "长度非0"
          fi

      - name: 运行翻译脚本
        run: |
          npx tsx scripts/translate.ts

      - name: git 配置和提交
        run: |
          git config --global user.email "12123@qq.com"
          git config --global user.name "我是Action"
          git status
          git add .
          git status
          git commit -m "测试翻译脚本提交"
          git push
