name: Test

on:
  push:
    branches:
      - main

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 创建目录
        run: |
          pwd
          mkdir testfile

      - name: 创建文件，写
        run: |
          echo "这是一段文本" > testfile/test.txt
          ls testfile
          cat testfile/test.txt

      - name: git命令
        run: |
          git config --global user.email "12123@qq.com"
          git config --global user.name "我是Action"
          git status
          git add .
          git status
          git commit -m "这是第一次Action运行"
          git push
